# Generated by Django 2.1.3 on 2018-11-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_contact_friends_+', to='chat.Contact'),
        ),
    ]
